### ISSUE TITLE
함수에 주석 달기

### ISSUE THREAD

**Issue by zrma** [xfrnk2/puyopuyo#11]
https://github.com/xfrnk2/puyopuyo/blob/d471ed03d9efc11d1487ffd9fe957ced3f59d0b7/src/main.py#L30

함수에 주석을 달아봅시다.

주석을 어떤 식으로 사용하는지 공부해 봅시다.
(작성 방식, 용도/목적 등등등)

**Comment by xfrnk2** [comment]
적당한 문구로 달아 놓았어요^^

**Comment by zrma** [comment]
@xfrnk2 #12 일감의 코멘트를 확인해 주세요 :)

**Comment by zrma** [comment]
@xfrnk2 고생하셨습니다 :)
