### ISSUE TITLE
문서에 주석 작성

### ISSUE THREAD

**Issue by zrma** [xfrnk2/puyopuyo#12]
https://github.com/xfrnk2/puyopuyo/blob/d471ed03d9efc11d1487ffd9fe957ced3f59d0b7/src/main.py#L1

#11 이 일감의 연계 일감입니다.
링크를 눌러서 확인해 봅시다.

**Comment by xfrnk2** [comment]
확인했어요

**Comment by zrma** [comment]
@xfrnk2 주석을 작성한 후 커밋 할 때 이 이슈의 번호를 커밋 메세지에 담아줍니다
#11 이렇게 적으시면 돼요.

그리고 완료 된 이슈는 Test로 넘겨주세요.

**Comment by xfrnk2** [comment]
네~~

**Comment by zrma** [comment]
@xfrnk2 고생하셨습니다 :)
