### ISSUE TITLE
pep 8에 대해서 학습하기

### ISSUE THREAD

**Issue by zrma** [xfrnk2/puyopuyo#14]
pep 8에 대해서 학습하고 그 결과를 이 글의 댓글로 달아주세요.

**Comment by xfrnk2** [comment]
규칙이며 기본적인 룰, 개선 제안서, 조사해보니 일종의 가이드라인이며 코딩을 위한 협약 같은 것 같습니다 :)

**Comment by zrma** [comment]
@xfrnk2 말씀하신 것은 PEP 에 대한 설명이고, PEP 8 그 중 일부입니다.

아래의 세 링크를 읽어주세요.

https://spoqa.github.io/2012/08/03/about-python-coding-convention.html
https://www.python.org/dev/peps/pep-0008/
http://www.hanul93.com/kicomav-pep8/

**Comment by zrma** [comment]
@xfrnk2 고생하셨습니다 :)
