### ISSUE TITLE
사용하지 않는 변수 무시하기

### ISSUE THREAD

**Issue by zrma** [xfrnk2/puyopuyo#15]
변수 대입, 분해 과정에서 사용하지 않는 변수는 _ 로 무시할 수 있습니다.

관련 용법을 공부해 봅시다.

**Comment by xfrnk2** [comment]
어서어서 사용해보고싶네요!

**Comment by zrma** [comment]
@xfrnk2 
#16 일감에도 언급했지만, 

To Do 에서 Done으로 바로 옮기지 마시고,
현재 진행 중인 과제는 Doing 으로 옮겨주세요.

그리고 구현이 완료 되었다면 Test 로 옮겨 주시면,
해당 Test 일감을 제가 확인 한 후 Done으로 옮기겠습니다. :)
